### ISSUE TITLE
AttributeError: module 'config' has no attribute 'librarydir'

### ISSUE THREAD

**Issue by codevirtuel** [de-odex/FruityBot#4]
Hello

i'm using python 3.6.2 on windows 10.
When I start bot.py I get this error : 

Traceback (most recent call last):
  File "bot.py", line 27, in <module>
    if not os.path.exists(config.librarydir + "/osulib"):
AttributeError: module 'config' has no attribute 'librarydir'

**Comment by de-odex** [comment]
Thanks, didn't catch that at first. Updated :P
